### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by edacval**
Rename package according AUR rules.
Bump version to 2.165.2.
Move runner working dir to /var/lib/github-actions.
Fix license.
Add sudo to dependencies.
Add .gitignore.
Fix source URL.
Silence ldd warnings
Disable service on package removal.
Other minor improvements.

### CODE REVIEW

**Comment by ioquatix** [comment]
This looks great to me, thanks for your help. Should I remove old package if the name is changed? What is best procedure?

Also, I see you changed root directory.

I had a lot of issues with this package using and installing weird shit (user files, source code) into the same directory as binaries, etc. Did you confirm this change works? Because my release was confirmed working in production.

**Comment by edacval** [comment]
> This looks great to me, thanks for your help. Should I remove old package if the name is changed? What is best procedure?

According to https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Requests, 
proper way is upload as new package and then create merge request in old package.

> Also, I see you changed root directory.

Yes, moved under /var/lib - same as jenkins , gitlab, drone runners.

> I had a lot of issues with this package using and installing weird shit (user files, source code) into the same directory as binaries, etc. 

When https://github.com/actions/runner/issues/246 will be solved, it will be possible to move {bin,externals} under  /usr/share/github-actions as read-only  and leave /var/lib/github-actions just to workflow content. Current status (writable executables, self-updating binaries, data and binaries in same folder) reminds me best times of Windows 95 :)

> Did you confirm this change works? Because my release was confirmed working in production.

Not tested in deep, basic tasks works same as previous version. Better to test in wm/container before moving to production.

**Comment by ioquatix** [comment]
I already run it in a container, so I can test it.

**Comment by ioquatix** [comment]
I submit merge request "github-actions" -> "github-actions-bin". Thanks for your help.

**Pull request merged**
